[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-color-spring-night'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = "lilydjwg/colorizer"
on_ft = 'css'

[[plugins]]
repo = "Yggdroot/indentLine"
