[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1

inoremap <silent><expr> <TAB>
\ pumvisible() ? "\<C-n>" :
\ <SID>check_back_space() ? "\<TAB>" :
\ deoplete#mappings#manual_complete()

function! s:check_back_space() abort "{{{
let col = col('.') - 1
return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'raphamorim/lucario'
hook_add = '''
colorscheme lucario
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=black
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=darkgrey
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2
'''

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = "lilydjwg/colorizer"

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = '''
let g:vim_markdown_better_folding=0
let g:vim_markdown_folding_disabled = 1
'''
