[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'jaapie/vim-colours-dusk'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/syntastic.git'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = 'go'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'nixprime/cpsm'
  [plugins.build]
  mac     = './install.sh'
  linux   = './install.sh'
  unix    = './install.sh'

[[plugins]]
repo = 'Shougo/vimproc.vim'
  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = "lilydjwg/colorizer"
on_ft = 'css'

[[plugins]]
repo = "othree/html5.vim"
on_ft = 'html'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'Shougo/unite-outline'

